main: "com.gmail.jyckosianjaya.easywhitelist.EasyWhiteList"
name: "EasyWhitelist"
description: "Easy whitelisting!"
version: "1.0.2"
api-version: "1.19"
authors: ["Gober"]
commands:
  "easywhitelist":
    aliases: ["easywl", "ewhitelist"]
    usage: "/<command>"